### ISSUE TITLE
Uncaught TypeError: Cannot read property 'rootDirectories' of undefined

### ISSUE THREAD

**Issue by zuhair-naqvi** [cakecatz/flex-toolbar#80] opened 2016-07-21 04:47 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.9.0-beta0
**System**: Mac OS X 10.11
**Thrown From**: [flex-tool-bar](https://github.com/cakecatz/flex-toolbar) package, v0.10.2

### Stack Trace

Uncaught TypeError: Cannot read property 'rootDirectories' of undefined

```
At /Users/zuhairnaqvi/.atom/packages/flex-tool-bar/lib/flex-tool-bar.coffee:91

TypeError: Cannot read property 'rootDirectories' of undefined
    at Object.module.exports.resolveProjectConfigPath (/Users/zuhairnaqvi/.atom/packages/flex-tool-bar/lib/flex-tool-bar.coffee:91:36)
    at Object.module.exports.switchProject (/Users/zuhairnaqvi/.atom/packages/flex-tool-bar/lib/flex-tool-bar.coffee:138:6)
    at /Users/zuhairnaqvi/.atom/packages/flex-tool-bar/lib/flex-tool-bar.coffee:118:10
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:284:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:433:21)
    at atom-tabs.TabBarView.onMouseDown (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:660:19)
```

### Commands

```
  2x -1:43.5.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
     -1:13.1.0 pane:reopen-closed-item (atom-text-editor.editor.is-focused)
     -1:06.5.0 application:add-project-folder (atom-text-editor.editor.is-focused)
     -1:04.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:01.6.0 core:select-all (atom-text-editor.editor.mini.is-focused)
  2x -1:01.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  5x -0:58.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  3x -0:56.6.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  2x -0:55.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  3x -0:55.3.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:54.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:53.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:53.7.0 settings-view:view-installed-packages (atom-text-editor.editor)
     -0:04.1.0 flex-tool-bar:edit-config-file (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
flex-tool-bar, v0.10.2 (active)
language-babel, v2.32.0 (active)
linter, v1.11.14 (active)
linter-eslint, v7.2.4 (active)
tool-bar, v1.0.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (active)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (active)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.2.0 (active)
git-diff, v1.0.1 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.3.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by jerone** [comment] 2016-07-21 08:26
Duplicate of https://github.com/cakecatz/flex-toolbar/issues/76

**Closed by jerone** 2016-07-21 08:26 UTC

**Comment by newelement** [comment] 2016-07-28 17:22
I still get this error even after uninstalling/reinstalling
