### ISSUE TITLE
Uncaught TypeError: Cannot read property 'findIndex' of null

### ISSUE THREAD

**Issue by eusebiosanz** [cakecatz/flex-toolbar#154] opened 2019-02-15 12:47 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Linux Mint
**Thrown From**: [flex-tool-bar](https://github.com/cakecatz/flex-toolbar) package 2.1.2

### Stack Trace

Uncaught TypeError: Cannot read property 'findIndex' of null

```
At /home/sanz/.atom/packages/flex-tool-bar/lib/flex-tool-bar.js:451

TypeError: Cannot read property 'findIndex' of null
    at ToolBarView.addItem (/packages/tool-bar/lib/tool-bar-view.js:74:28)
    at ToolBarManager.addButton (/packages/tool-bar/lib/tool-bar-manager.js:13:22)
    at /packages/flex-tool-bar/lib/types/button.js:14:17)
    at Object.addButtons (/packages/flex-tool-bar/lib/flex-tool-bar.js:506:40)
    at Object.reloadToolbar (/packages/flex-tool-bar/lib/flex-tool-bar.js:443:9)
    at Object.onDidChangeItem (/packages/flex-tool-bar/lib/flex-tool-bar.js:366:8)
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1190133)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1191574)
    at Workspace.didActivatePaneContainer (/usr/share/atom/resources/app/static/<embedded>:11:424039)
    at WorkspaceCenter.paneContainer.onDidActivatePane (/usr/share/atom/resources/app/static/<embedded>:14:38543)
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1190133)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1191574)
    at PaneContainer.didActivatePane (/usr/share/atom/resources/app/static/<embedded>:11:446225)
    at Pane.activate (/usr/share/atom/resources/app/static/<embedded>:11:463550)
    at /packages/pdf-view/lib/pdf-editor-view.js:183:40)
    at HTMLDivElement.dispatch (/packages/clipboard-plus/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/clipboard-plus/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -7:52.5.0 snippets:next-tab-stop (input.hidden-input)
     -7:52.5.0 snippets:expand (input.hidden-input)
     -7:52.5.0 editor:indent (input.hidden-input)
  7x -7:50.4.0 core:backspace (input.hidden-input)
     -7:37.9.0 autocomplete-plus:confirm (input.hidden-input)
     -7:37.9.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -7:35.5.0 intentions:highlight (input.hidden-input)
     -7:35.1.0 core:undo (input.hidden-input)
     -7:33.2.0 docblockr:parse-enter (input.hidden-input)
     -7:33.2.0 editor:newline (input.hidden-input)
     -7:31.7.0 intentions:highlight (input.hidden-input)
     -7:31.2.0 core:undo (input.hidden-input)
  3x -7:28.7.0 core:backspace (input.hidden-input)
     -7:12.2.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -6:52.5.0 core:delete (input.hidden-input)
     -1:23.3.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
aligner-javascript 1.3.0 
aligner-php 1.3.0 
ask-stack 2.2.0 
atom-autocomplete-php 0.25.6 
atom-background-pic 2.0.7 
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-live-server 2.3.0 
atom-lorempixel 0.1.0 
atom-webstorm 0.0.2 
autoclose-html 0.23.0 
autocomplete 0.47.0 
autocomplete-html-entities 0.2.0 
autocomplete-java 1.2.7 
autocomplete-json 5.5.2 
autocomplete-modules 2.2.6 
autocomplete-paths 2.12.2 
autocomplete-php 0.3.7 
autocomplete-python 1.12.0 
autoprefixer 3.7.1 
busy-signal 2.0.0 
click-link 1.0.11 
clipboard-plus 0.5.1 
color-picker 2.3.0 
docblockr 0.13.7 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
emmet-snippets-compatibility 1.0.6 
es6-javascript 1.0.0 
file-icons 2.1.29 
flex-tool-bar 2.1.2 
french-menu 0.2.2 
git-control 0.9.0 
git-history 3.3.0 
git-plus 8.6.1 
git-time-machine 2.1.0 
highlight-selected 0.14.0 
html-template-generator 0.3.0 
html-to-css 0.2.2 
ide-php 0.7.18 
intentions 1.1.5 
javascript-snippets 1.2.1 
language-javascript-jsx 0.3.7 
language-jolie 0.5.0 
language-pseudocodefr 0.1.0 
language-vue 0.24.0 
linter 2.3.0 
linter-jolie 0.8.0 
linter-jscs 4.2.1 
linter-jshint 3.1.14 
linter-julia 0.7.3 
linter-sass-lint 1.9.0 
linter-tidy 2.4.0 
linter-ui-default 1.7.1 
lorem 4.0.0 
markdown-pdf 2.2.0 
minimap 4.29.9 
minimap-pigments 0.2.2 
pdf-view 0.71.0 
php-cs-fixer 4.1.1 
php-integrator-autocomplete-plus 1.6.2 
php-integrator-tooltips-legacy-php56 1.1.6 
pigments 0.40.2 
prettier-atom 0.56.3 
script 3.18.1 
split-diff 1.6.0 
svg-icons 0.5.3 
teletype 0.13.3 
todo 0.6.0 
tool-bar 1.1.11 
tool-bar-atom 1.7.0 
turbo-javascript 1.4.0 
```

**Comment by UziTech** [comment] 2019-02-15 13:33
Can you share your config file?

**Comment by UziTech** [comment] 2019-02-15 15:31
It looks like the issue is with the `tool-bar` package

>     at ToolBarView.addItem (/packages/tool-bar/lib/tool-bar-view.js:74:28)

https://github.com/suda/tool-bar/blob/master/lib/tool-bar-view.js#L74

the only time `this.items` is null is when it is destroyed.

You should be able to fix this be restarting Atom

**Comment by UziTech** [comment] 2019-03-05 19:56
I'm going to close this as it doesn't seem to be something I can fix.

**Closed by UziTech** 2019-03-05 19:56 UTC
Labels: needs more information, tool-bar
